steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  dir: 'Dcube.Quoestionnaire.Ui'
  args: ['build', '-t', 'ui', '.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/UI:$COMMIT_SHA']

options:
  logging: CLOUD_LOGGING_ONLY

