steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  dir: 'Dcube.Quoestionnaire.Ui'
  args: ['build', '-t', 'ui', '.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$PROJECT_ID/Dcube.Quoestionnaire.Ui:latest', '.']
  dir: 'ui'  # Optional: directory containing Dockerfile

options:
  logging: CLOUD_LOGGING_ONLY

