steps:
  # Build the Docker image with full GCR tag
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'Dcube.Quoestionnaire.Ui'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ui:$COMMIT_SHA', '.']
    
  # Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'x/$PROJECT_ID/ui:$COMMIT_SHA']


options:
  logging: CLOUD_LOGGING_ONLY

