steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  dir: 'Dcube.Quoestionnaire.Ui'
  args: ['build', '-t', 'ui1', '.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ui:latest', '.']
  dir: 'ui'  # Optional: directory containing Dockerfile

options:
  logging: CLOUD_LOGGING_ONLY

