apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
      - name: ui-container
        image: us-central1-docker.pkg.dev/hip-return-462813-t1/q-test/ui:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "70m"
          limits:
            memory: "128Mi"
            cpu: "300m"
        volumeMounts:
        - name: ui-config-volume
          mountPath: /usr/share/nginx/html/assets/api-constants.json
          subPath: api-constants.json
      volumes:
      - name: ui-config-volume
        configMap:
          name: ui-config
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
