apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui-app

spec:
  replicas: 1      
  selector:               
    matchLabels:          
      app: ui-app
  template:
    metadata:
     labels:
      app: ui-app
    spec:
     containes:
    - name : ui-container
      image: 
      ports:
      - containerPort: 80
---      
apiVersion: v1
kind: Service
metadata:
  name: ui-deployment
spec:
  selector:
    app: ui-app
  ports:
    - port: 80
      targetPort: 80
     
    
      
