name: 'Build and Deploy to GKE'

on:
  push:
    branches:
      - '"main"'

env:
  PROJECT_ID: 'hip-return-462813-t1' # TODO: update to your Google Cloud project ID
  GAR_LOCATION: 'us-central1' # TODO: update to your region
  GKE_CLUSTER: 'cluster-1' # TODO: update to your cluster name
  GKE_ZONE: 'us-central1-a' # TODO: update to your cluster zone
  DEPLOYMENT_NAME: 'gke-test' # TODO: update to your deployment name
  REPOSITORY: 'us-central1-docker.pkg.dev/hip-return-462813-t1/q-test' # TODO: update to your Artifact Registry docker repository nam
  
jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'Dev'
    
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      # Step 2: Authenticate to Google Cloud
      - name: Set up Google Cloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.TES_GHL }}
          
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker REGION-docker.pkg.dev --quiet
          
        
       # Build the Docker image
      - name: 'Build and push Docker container'
        run: |-
          docker build tag "${{ REPOSITORY }}":${{ github.sha }}  ui .
          docker push "${{ REPOSITORY }}":${{ github.sha }}" 
        



